### ISSUE TITLE
Can't compile the project

### ISSUE THREAD

**Issue by nptriet** [k1ckdown/MovieCatalog#1]
Hi. I'm newbie as ios developer. Can u guys tell me how to solve this error? I can't run the project. Thanks in advance.
![Screenshot at Dec 02 17-27-23](https://github.com/k1ckdown/MovieCatalog/assets/3799327/2976b787-c9f1-43ee-ada2-5b81ff404d3b)

**Comment by k1ckdown** [comment]
Try clean build folder (Command + Shift + K). Which Xcode version are you using?

**Comment by k1ckdown** [comment]
Try clean build folder (Command + Shift + K). Which Xcode version are you using?

**Comment by nptriet** [comment]
I try it but still not work @k1ckdown :'( Im using xcode 14.1.3

**Comment by k1ckdown** [comment]
@nptriet You need at least Xcode 15 to build the project

**Comment by nptriet** [comment]
Thank you. I will try it.
