### ISSUE TITLE
Realm Error 

### ISSUE THREAD

**Issue by avazbekolimov07** [k1ckdown/MovieCatalog#2]
Realm part is giving error by terminating runtime :

RealmSwift/Realm.swift:1468: Precondition failed: Incorrect actor executor assumption; Expected 'UnownedSerialExecutor(executor: (Opaque Value))' executor.

**Comment by k1ckdown** [comment]
@avazbekolimov07 You're right, this worked in iOS 16, but in iOS 17 it was crashing. The reason is that Realm is used outside of the actor which it is isolated to. I'll fix this soon.
