### ISSUE TITLE
Coordinator nested navigation destination..

### ISSUE THREAD

**Issue by sherwin14** [k1ckdown/MovieCatalog#4]
Hi, I am currently following this pattern. I would like to ask if this pattern supports nested navigations..  Like for example new navigation destination after MovieDetailsView(id: String).. 

Thank you.

**Comment by k1ckdown** [comment]
Hi. You can add a router for the MovieDetails module, which will have closures for navigation to the next screens. Closures will be created by the CoordinatorView and passed to MovieDetails. Each CoordinatorView is associated with one Navigation Stack.

**Comment by sherwin14** [comment]
Thank you @k1ckdown , I'll try it.
